import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import './chatList.css';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@clerk/react';
import { useApi } from '../../lib/api';

const ChatList = ({ onClose }) => {
  const { getToken, isLoaded, userId } = useAuth(); const { apiFetch } = useApi(); const queryClient = useQueryClient(); const navigate = useNavigate(); const location = useLocation();
  const [openMenuId, setOpenMenuId] = useState(null); const [editingChatId, setEditingChatId] = useState(null); const [editingTitle, setEditingTitle] = useState(''); const [isSearching, setIsSearching] = useState(false); const [searchTerm, setSearchTerm] = useState(''); const [notice, setNotice] = useState('');
  const { isPending, error, data = [] } = useQuery({ queryKey: ['userChats'], enabled: isLoaded && !!userId, queryFn: async () => { const token = await getToken(); if (!token) throw new Error('Please sign in again to load chats.'); const response = await fetch(`${import.meta.env.VITE_API_URL}/api/userchats`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(response.status === 401 ? 'Your session has expired. Please sign in again.' : 'Unable to load conversations.'); return response.json(); } });
  const chatMutation = useMutation({ onMutate: async ({ id, payload, action }) => { await queryClient.cancelQueries({ queryKey: ['userChats'] }); const previousChats = queryClient.getQueryData(['userChats']); queryClient.setQueryData(['userChats'], chats => action === 'delete' ? chats?.filter(chat => chat._id !== id) : chats?.map(chat => chat._id === id ? { ...chat, ...payload } : chat)); return { previousChats }; }, mutationFn: async ({ id, action, payload }) => { const response = await apiFetch(`${import.meta.env.VITE_API_URL}${action === 'delete' ? `/api/chats/${id}` : `/api/userchats/${id}`}`, { method: action === 'delete' ? 'DELETE' : 'PATCH', ...(payload && { body: JSON.stringify(payload) }) }); if (!response.ok) throw new Error(action === 'delete' ? 'Unable to delete this chat.' : 'Unable to save chat changes.'); }, onSuccess: (_result, variables) => { queryClient.invalidateQueries({ queryKey: ['userChats'] }); setOpenMenuId(null); setEditingChatId(null); if (variables.action === 'delete' && location.pathname.endsWith(variables.id)) navigate('/dashboard'); }, onError: (mutationError, _variables, context) => { if (context?.previousChats) queryClient.setQueryData(['userChats'], context.previousChats); setNotice(mutationError.message); } });
  const visibleChats = useMemo(() => data.filter(chat => chat.title.toLowerCase().includes(searchTerm.trim().toLowerCase())), [data, searchTerm]);
  useEffect(() => {
    const openSearch = event => {
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault(); setIsSearching(true);
      }
    };
    window.addEventListener('keydown', openSearch);
    return () => window.removeEventListener('keydown', openSearch);
  }, []);
  const go = path => { navigate(path); if (window.matchMedia('(max-width: 760px)').matches) onClose(); }; const newChat = () => go('/dashboard');
  const saveRename = id => { if (!editingTitle.trim()) return setNotice('A chat title is required.'); chatMutation.mutate({ id, action: 'update', payload: { title: editingTitle } }); };
  const renderChat = chat => { const active = location.pathname.endsWith(chat._id); return <div className={`chatRow${active ? ' active' : ''}`} key={chat._id}>{editingChatId === chat._id ? <form className="renameForm" onSubmit={e => { e.preventDefault(); saveRename(chat._id); }}><input value={editingTitle} onChange={e => setEditingTitle(e.target.value)} maxLength={80} autoFocus aria-label="Chat title" /><button type="submit" disabled={chatMutation.isPending}>Save</button><button type="button" onClick={() => setEditingChatId(null)}>Cancel</button></form> : <button className="chatLink" type="button" onClick={() => go(`/dashboard/chats/${chat._id}`)} aria-current={active ? 'page' : undefined}><span className="chatTitle">{chat.title}</span>{chat.pinned && <span className="pinMark">⌖</span>}</button>}{editingChatId !== chat._id && <div className="chatActions"><button className="moreButton" type="button" aria-label={`More options for ${chat.title}`} aria-expanded={openMenuId === chat._id} onClick={() => { setOpenMenuId(openMenuId === chat._id ? null : chat._id); setNotice(''); }}>•••</button>{openMenuId === chat._id && <div className="chatMenu" role="menu"><button type="button" role="menuitem" onClick={() => { setEditingChatId(chat._id); setEditingTitle(chat.title); setOpenMenuId(null); }}>Rename</button><button type="button" role="menuitem" onClick={() => chatMutation.mutate({ id: chat._id, action: 'update', payload: { pinned: !chat.pinned } })}>{chat.pinned ? 'Unpin' : 'Pin'}</button><button className="danger" type="button" role="menuitem" onClick={() => { if (window.confirm(`Delete “${chat.title}”? This cannot be undone.`)) chatMutation.mutate({ id: chat._id, action: 'delete' }); }}>Delete</button></div>}</div>}</div>; };
  const displayChats = data.filter(chat => !chat.archived);
  return <div className="chatList"><div className="sidebarTop"><button className="brandButton" type="button" onClick={newChat} aria-label="Start a new chat"><img src="/assets/logo.png" alt="" /><span>Nexa AI</span></button><button className="closeButton" type="button" onClick={onClose} aria-label="Collapse sidebar" title="Collapse sidebar">‹</button></div><button className="newChatButton" type="button" onClick={newChat}>＋ <span>New chat</span></button><button className="searchButton" type="button" onClick={() => { setIsSearching(true); setNotice(''); }} aria-label="Search chats">⌕ <span>Search chats</span><kbd>Ctrl K</kbd></button>{isSearching ? <div className="searchPanel"><div className="searchInputWrap"><span>⌕</span><input autoFocus value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder="Search conversations" aria-label="Search conversations" /><button type="button" onClick={() => { setIsSearching(false); setSearchTerm(''); }} aria-label="Close search">×</button></div><div className="searchResults">{isPending ? <p>Searching conversations…</p> : error ? <p role="alert">{error.message}</p> : !searchTerm.trim() ? <p>Type to search your conversations.</p> : visibleChats.length ? visibleChats.map(renderChat) : <p>No conversations found.</p>}</div></div> : <><div className="sectionHeader">Recent chats</div><div className="list recentList">{isPending ? <p className="listStatus">Loading conversations…</p> : error ? <div className="listStatus" role="alert"><p>{error.message}</p><button type="button" onClick={() => queryClient.invalidateQueries({ queryKey: ['userChats'] })}>Try again</button></div> : displayChats.length ? displayChats.map(renderChat) : <p className="listStatus">No conversations yet.</p>}</div></>}{notice && <div className="chatNotice" role="status">{notice}</div>}</div>;
};
export default ChatList;
